version: "3"
services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        # задаем пароль для root пользователя
        environment:
            SA_PASSWORD: "aA123456789"
            ACCEPT_EULA: "Y"