// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepWatcher.Data.Context;

namespace SleepWatcher.Data.Migrations
{
    [DbContext(typeof(SleepWatcherContext))]
    partial class SleepWatcherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SleepWatcher.Core.Entities.DTO.SleepTimeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BeginSleepTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndSleepTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeginSleepTime", "EndSleepTime")
                        .IsUnique();

                    b.ToTable("SleepTimeSettings");
                });

            modelBuilder.Entity("SleepWatcher.Core.Entities.DTO.User", b =>
                {
                    b.Property<string>("VkId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int?>("SleepTimeSettingId")
                        .HasColumnType("int");

                    b.HasKey("VkId");

                    b.HasIndex("SleepTimeSettingId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SleepWatcher.Core.Entities.DTO.User", b =>
                {
                    b.HasOne("SleepWatcher.Core.Entities.DTO.SleepTimeSetting", "SleepTimeSetting")
                        .WithMany()
                        .HasForeignKey("SleepTimeSettingId");

                    b.Navigation("SleepTimeSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
